// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: service-definition.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DEXStreamerClient is the client API for DEXStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DEXStreamerClient interface {
	StreamContract(ctx context.Context, in *Contract, opts ...grpc.CallOption) (DEXStreamer_StreamContractClient, error)
}

type dEXStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewDEXStreamerClient(cc grpc.ClientConnInterface) DEXStreamerClient {
	return &dEXStreamerClient{cc}
}

func (c *dEXStreamerClient) StreamContract(ctx context.Context, in *Contract, opts ...grpc.CallOption) (DEXStreamer_StreamContractClient, error) {
	stream, err := c.cc.NewStream(ctx, &DEXStreamer_ServiceDesc.Streams[0], "/DEXStreamer/StreamContract", opts...)
	if err != nil {
		return nil, err
	}
	x := &dEXStreamerStreamContractClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DEXStreamer_StreamContractClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type dEXStreamerStreamContractClient struct {
	grpc.ClientStream
}

func (x *dEXStreamerStreamContractClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DEXStreamerServer is the server API for DEXStreamer service.
// All implementations must embed UnimplementedDEXStreamerServer
// for forward compatibility
type DEXStreamerServer interface {
	StreamContract(*Contract, DEXStreamer_StreamContractServer) error
	mustEmbedUnimplementedDEXStreamerServer()
}

// UnimplementedDEXStreamerServer must be embedded to have forward compatible implementations.
type UnimplementedDEXStreamerServer struct {
}

func (UnimplementedDEXStreamerServer) StreamContract(*Contract, DEXStreamer_StreamContractServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamContract not implemented")
}
func (UnimplementedDEXStreamerServer) mustEmbedUnimplementedDEXStreamerServer() {}

// UnsafeDEXStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DEXStreamerServer will
// result in compilation errors.
type UnsafeDEXStreamerServer interface {
	mustEmbedUnimplementedDEXStreamerServer()
}

func RegisterDEXStreamerServer(s grpc.ServiceRegistrar, srv DEXStreamerServer) {
	s.RegisterService(&DEXStreamer_ServiceDesc, srv)
}

func _DEXStreamer_StreamContract_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Contract)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DEXStreamerServer).StreamContract(m, &dEXStreamerStreamContractServer{stream})
}

type DEXStreamer_StreamContractServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type dEXStreamerStreamContractServer struct {
	grpc.ServerStream
}

func (x *dEXStreamerStreamContractServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// DEXStreamer_ServiceDesc is the grpc.ServiceDesc for DEXStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DEXStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DEXStreamer",
	HandlerType: (*DEXStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamContract",
			Handler:       _DEXStreamer_StreamContract_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service-definition.proto",
}
